package top.ellan.mahjong.rules.riichi.engine;

public enum RuleViolation {
    FIFTH_KAN_FORBIDDEN,
    REACTION_ALREADY_SUBMITTED,
    REACTION_NOT_AVAILABLE,
    INVALID_REACTION_PAYLOAD,
    REACTION_WINDOW_CLOSED,
    ILLEGAL_PHASE,
    UNKNOWN_PLAYER,
    NOT_YOUR_TURN,
    TILE_NOT_IN_HAND,
    KUIKAE_FORBIDDEN,
    INSUFFICIENT_POINTS,
    NOT_TENPAI,
    FURITEN,
    NO_YAKU,
    MINIMUM_HAN_NOT_MET,
    UNSUPPORTED_RULE_FLOW,
    EVALUATION_FAILED
}
