back=riichi:tile/back
1m=riichi:tile/1m
2m=riichi:tile/2m
3m=riichi:tile/3m
4m=riichi:tile/4m
5m=riichi:tile/5m
6m=riichi:tile/6m
7m=riichi:tile/7m
8m=riichi:tile/8m
9m=riichi:tile/9m
5mr=riichi:tile/5mr
1p=riichi:tile/1p
2p=riichi:tile/2p
3p=riichi:tile/3p
4p=riichi:tile/4p
5p=riichi:tile/5p
6p=riichi:tile/6p
7p=riichi:tile/7p
8p=riichi:tile/8p
9p=riichi:tile/9p
5pr=riichi:tile/5pr
1s=riichi:tile/1s
2s=riichi:tile/2s
3s=riichi:tile/3s
4s=riichi:tile/4s
5s=riichi:tile/5s
6s=riichi:tile/6s
7s=riichi:tile/7s
8s=riichi:tile/8s
9s=riichi:tile/9s
5sr=riichi:tile/5sr
1z=riichi:tile/1z
2z=riichi:tile/2z
3z=riichi:tile/3z
4z=riichi:tile/4z
5z=riichi:tile/5z
6z=riichi:tile/6z
7z=riichi:tile/7z
stick.p100=riichi:stick/p100
stick.p1000=riichi:stick/p1000
stick.p5000=riichi:stick/p5000
stick.p10000=riichi:stick/p10000
