back=riichi:tile/back
1m=riichi:tile/m1
2m=riichi:tile/m2
3m=riichi:tile/m3
4m=riichi:tile/m4
5m=riichi:tile/m5
6m=riichi:tile/m6
7m=riichi:tile/m7
8m=riichi:tile/m8
9m=riichi:tile/m9
5mr=riichi:tile/m5_red
1p=riichi:tile/p1
2p=riichi:tile/p2
3p=riichi:tile/p3
4p=riichi:tile/p4
5p=riichi:tile/p5
6p=riichi:tile/p6
7p=riichi:tile/p7
8p=riichi:tile/p8
9p=riichi:tile/p9
5pr=riichi:tile/p5_red
1s=riichi:tile/s1
2s=riichi:tile/s2
3s=riichi:tile/s3
4s=riichi:tile/s4
5s=riichi:tile/s5
6s=riichi:tile/s6
7s=riichi:tile/s7
8s=riichi:tile/s8
9s=riichi:tile/s9
5sr=riichi:tile/s5_red
1z=riichi:tile/east
2z=riichi:tile/south
3z=riichi:tile/west
4z=riichi:tile/north
5z=riichi:tile/white_dragon
6z=riichi:tile/green_dragon
7z=riichi:tile/red_dragon
stick.p100=riichi:stick/p100
stick.p1000=riichi:stick/p1000
stick.p5000=riichi:stick/p5000
stick.p10000=riichi:stick/p10000
